services:
  db:
    container_name: f8-database-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - '5000:5432'
    volumes:
      - ./db:/var/lib/postgresql/data


#  db:
#    container_name: f8-database-mysql
#    image: mysql:9.3.0
#    environment:
#      MYSQL_ROOT_PASSWORD: mysql
#      MYSQL_USER: user
#      MYSQL_PASSWORD: mysql
#      MYSQL_DATABASE: default
#    volumes:
#      - ./db:/var/lib/mysql